### ISSUE TITLE
Crashes right at start

### ISSUE THREAD

**Issue by Tony-il-Capo** [scheich/Throughput#4]
Hi there
Not much to say, app crashes right after starting it with message "Unfortunately Throughput has stopped"
Last version form F-Droid, Sony Xperia S aka Lt26i, Android 4.1.2

**Comment by scheich** [comment]
Can you provide the log messages?

**Comment by Tony-il-Capo** [comment]
See if this help
Quick filtered Debug logcat

```
Android Device Log - Mar 12, 2017 1:06:50 AM
#Created by Quick System Info PRO version 3.6.4

Device: LT26i
CPU+ABI: armeabi-v7a
CPU+ABI2: armeabi
Release: 4.1.2
SDK: 16 (Jelly Bean)

#Private device information above removed, log below was filtered to Throughput (PID) only

03-12 01:05:07.122 E/Trace   (11302) :	error opening trace file: No such file or directory (2)
03-12 01:05:07.122 D/ActivityThread(11302) :	setTargetHeapUtilization:0.25
03-12 01:05:07.122 D/ActivityThread(11302) :	setTargetHeapIdealFree:8388608
03-12 01:05:07.122 D/ActivityThread(11302) :	setTargetHeapConcurrentStart:2097152
03-12 01:05:07.192 I/dalvikvm(11302) :	Could not find method android.provider.Settings$Global.getInt, referenced from method de.mangelow.throughput.NotificationService.isAirplaneModeOn
03-12 01:05:07.192 W/dalvikvm(11302) :	VFY: unable to resolve static method 113: Landroid/provider/Settings$Global;.getInt (Landroid/content/ContentResolver;Ljava/lang/String;I)I
03-12 01:05:07.192 D/dalvikvm(11302) :	VFY: replacing opcode 0x71 at 0x001d
03-12 01:05:07.192 I/dalvikvm(11302) :	Could not find method android.app.Notification$Builder.setColor, referenced from method de.mangelow.throughput.NotificationService.modifyNotification
03-12 01:05:07.192 W/dalvikvm(11302) :	VFY: unable to resolve virtual method 4: Landroid/app/Notification$Builder;.setColor (I)Landroid/app/Notification$Builder;
03-12 01:05:07.192 D/dalvikvm(11302) :	VFY: replacing opcode 0x6e at 0x0077
03-12 01:05:07.202 W/SignalStrength(11302) :	Size of signalstrength parcel:172
03-12 01:05:07.222 D/AndroidRuntime(11302) :	Shutting down VM
03-12 01:05:07.222 W/dalvikvm(11302) :	threadid=1: thread exiting with uncaught exception (group=0x416b6378)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	FATAL EXCEPTION: main
03-12 01:05:07.222 E/AndroidRuntime(11302) :	java.lang.NoSuchMethodError: android.app.Notification$Builder.setColor
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at de.mangelow.throughput.NotificationService.modifyNotification(NotificationService.java:668)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at de.mangelow.throughput.NotificationService.onCreate(NotificationService.java:129)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2384)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.app.ActivityThread.access$1600(ActivityThread.java:138)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.os.Looper.loop(Looper.java:213)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at android.app.ActivityThread.main(ActivityThread.java:4787)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at java.lang.reflect.Method.invokeNative(Native Method)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at java.lang.reflect.Method.invoke(Method.java:511)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
03-12 01:05:07.222 E/AndroidRuntime(11302) :	at dalvik.system.NativeStart.main(Native Method)
03-12 01:05:08.682 I/Process (11302) :	Sending signal. PID: 11302 SIG: 9
```

**Comment by scheich** [comment]
OK, seems to have problems to determinate air plane mode state in your device, will take a look at it
